version: '3'
services:
    mongodb:
        image: mongo:3.6.23
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: oui
            MONGO_INITDB_ROOT_PASSWORD: password
    
