/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AdminToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0AuthExtUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0ClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0ClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0Domain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Backend": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "CloudinaryApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CloudinaryApiSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CloudinaryCloudName": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CloudinaryFolder": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "HashSalt": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IdTokenNamespace": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MongodbUri": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Redis": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "SendgridApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SendgridContactMail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SendgridContactTemplate": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SendgridGenericTemplate": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Uploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Vpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "WebhookApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}