const FilterValues = {
    STRING: 'STRING',
    BOOLEAN: 'BOOLEAN',
    NUMBER: 'NUMBER',
    RATING: 'RATING',
    DATE: 'DATE',
    GENDER: 'GENDER',
    NATIONALITY: 'NATIONALITY',
    COUNTRY: 'COUNTRY',
    PARTICIPATION_TYPE: 'PARTICIPATION_TYPE',
    LANGUAGE: 'LANGUAGE',
    STATUS: 'STATUS',
    TAG: 'TAG',
}

module.exports = FilterValues
