export const CONTAINS_SEARCH = 'contains-search'
export const FUZZY_SEARCH = 'fuzzy-search'
export const EXACT_SEARCH = 'exact-search'
export const SINGLE_SELECT = 'single-select'
export const MULTIPLE_SELECT = 'multiple-select'
